"""empty message

Revision ID: 580cc75be6b2
Revises: 
Create Date: 2024-04-12 18:28:46.022629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580cc75be6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('done')

    # ### end Alembic commands ###
